import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { AppProvider } from "./components/AppContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Toaster
            toastOptions={{
              style: {
                backgroundColor: "#696A6A",
                color: "white"
              },
            }}
          />
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
